import os
import shutil
from pathlib import Path

# Define source and destination
PROJECT_ROOT = Path(r"c:\Users\KIIT0001\Desktop\projects\DeCodeX")
SUBMISSION_DIR = PROJECT_ROOT / "submission_package"

# Create submission directory if it doesn't exist
if SUBMISSION_DIR.exists():
    shutil.rmtree(SUBMISSION_DIR)
SUBMISSION_DIR.mkdir(parents=True, exist_ok=True)

# Define structure
structure = {
    "1_Executive_Summary": [
        "Final_Submission/Final_Submission_Report.md"
    ],
    "2_Strategic_Reports": [
        "AUDIT_SUMMARY_AND_FINDINGS.md",
        "COMPREHENSIVE_AUDIT_AND_REANALYSIS.md",
        "EXECUTIVE_ACTION_PLAN.md",
        "QUICK_REFERENCE_GUIDE.md"
    ],
    "3_Interactive_Dashboard": {
        "type": "dir",
        "source": "docs",
        "dest": "dashboard"
    },
    "4_Data_Workspace": [
        "Final_Submission/DeCodeX_VoltRide_Analysis_Workspace.xlsx"
    ],
    "5_Source_Code": {
        "type": "dir",
        "source": "scripts",
        "dest": "scripts"
    }
}

print(f"Preparing submission package in {SUBMISSION_DIR}...")

# Copy files
for folder, items in structure.items():
    dest_folder = SUBMISSION_DIR / folder
    dest_folder.mkdir(exist_ok=True)
    
    if isinstance(items, list):
        for item in items:
            src = PROJECT_ROOT / item
            if src.exists():
                shutil.copy2(src, dest_folder / src.name)
                print(f"Copied {src.name} to {folder}")
            else:
                print(f"WARNING: Feature file {item} not found!")
    elif isinstance(items, dict) and items["type"] == "dir":
        src = PROJECT_ROOT / items["source"]
        dest = dest_folder / items["dest"] # Put inside the numbered folder
        if src.exists():
            shutil.copytree(src, dest)
            print(f"Copied directory {items['source']} to {folder}/{items['dest']}")
        else:
            print(f"WARNING: Directory {items['source']} not found!")

# Copy app.js separately to source code if needed, but it's in docs/assets/js which is in dashboard. 
# Let's verify app.js is in docs. Yes it is.

# Create a README for the submission
with open(SUBMISSION_DIR / "SUBMISSION_README.md", "w", encoding="utf-8") as f:
    f.write("""# DeCodeX 2026 Submission - VoltRide Analysis
**Submitted by:** Priyobrata Chatterjee (Roll: 23052904)

## Package Contents

### 1. Executive Summary
- **Final_Submission_Report.md**: The high-level overview of the analysis, strategy, and recommendations.

### 2. Strategic Reports
- **Audit Findings**: Detailed breakdown of the data errors and operational failures.
- **Comprehensive Audit**: Full analytical report.
- **Action Plan**: Step-by-step implementation guide.
- **Quick Reference**: "Cheat Sheet" for key metrics and fixes.

### 3. Interactive Dashboard
- Open **dashboard/index.html** in any web browser to view the interactive data visualization.

### 4. Data Workspace
- **Excel Workspace**: The raw data and manual calculations.

### 5. Source Code
- Python scripts used for data cleaning and analysis.

---
*Generated by DeCodeX Project Assistant*
""")

print("Submission package created successfully.")
